# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    tags: "v*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Metadata
      run: |
        if ${{ startsWith(github.ref, 'refs/tags/v') }}; then
          echo "BUILD_VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"
        else
          echo "BUILD_VERSION=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
        fi

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Package
      run: tar czf "dr-feeder-${BUILD_VERSION}-${{ matrix.os }}.tar.gz" "./dr-feeder" "./config.yaml"

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.tar.gz"
